---
title: "Exercise: Markdown"
author: "Environmental Data Analytics | John Fay and Luana Lima "
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
toc: TRUE
---
\listoftables 

## Set up the coding environment

```{r setup, warning=FALSE, include=FALSE, echo=FALSE}
#Load packages
library(tidyverse);library(here);library(lubridate)

#Load data
nutrient_data_raw <- read.csv(
  here('Data/Processed_KEY','NTL-LTER_Lake_Nutrients_PeterPaul_Processed.csv'),
  stringsAsFactors = TRUE)

#Fix dates
nutrient_data_raw$sampledate = ymd(nutrient_data_raw$sampledate)

```
The raw dataset has 'r nrow(nutrient_data_raw)' rows and 'r ncol(nutrient_data_raw)' columns.

>When the above it knit it takes the r code and runs it inside of the sentence

## Wrangle the data

```{r wrangle}
#Subset columns and rows
nutrient_data <- nutrient_data_raw %>% 
  select(-c(lakeid,depth_id,comments)) %>% 
  filter(depth == 0) %>% 
  drop_na()

#Compute summary stats for total nitrogen
nutrient_data_tn <- nutrient_data %>% 
  group_by(lakename) %>% 
  summarize(
    mean_tn_ug = mean(tn_ug),
    min_tn_ug = min(tn_ug),
    max_tn_ug = max(tn_ug),
    sd_tn_ug = sd(tn_ug)
  )
```

\newpage

## Report the summary

```{r Turning the report into table when knit, echo=FALSE}
#use the kable command knitr::kable allows you to use kable without loading the full knitr package
knitr::kable(nutrient_data_tn)

#add column names 
knitr::kable(nutrient_data_tn, col.names = c("A", "B", "C"))

#add caption - if you have another table it will automatically name it table 2
knitr::kable(nutrient_data_tn, caption = "Summary of Total Nitrogen")
knitr::kable(nutrient_data_tn, caption = "Another Summary of Total Nitrogen")

```

